# Generated by Django 3.0.5 on 2020-12-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
