# Generated by Django 3.0.5 on 2021-01-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labels',
            name='desc',
        ),
    ]
