# Generated by Django 3.0.5 on 2020-12-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_notes_isdelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
