# Generated by Django 3.0.5 on 2021-01-01 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_remove_labels_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='label',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Notes.Labels'),
        ),
    ]
