# Generated by Django 3.0.5 on 2021-01-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0006_auto_20210102_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='label',
        ),
        migrations.AddField(
            model_name='notes',
            name='label',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Notes.Labels'),
        ),
    ]
