# Generated by Django 3.0.5 on 2021-01-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0007_auto_20210102_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='label',
        ),
        migrations.AddField(
            model_name='notes',
            name='label',
            field=models.ManyToManyField(default=2, to='Notes.Labels'),
        ),
    ]
