# Generated by Django 3.0.5 on 2021-01-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0009_auto_20210102_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='label',
            field=models.ManyToManyField(to='Notes.Labels'),
        ),
    ]
