# Generated by Django 3.0.5 on 2021-01-14 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210107_2349'),
        ('Notes', '0010_auto_20210103_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='collaborator',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='collaborator', to='authentication.User'),
            preserve_default=False,
        ),
    ]
