# Generated by Django 3.0.5 on 2021-01-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210107_2349'),
        ('Notes', '0012_auto_20210114_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='collaborator',
        ),
        migrations.AddField(
            model_name='notes',
            name='collaborator',
            field=models.ManyToManyField(blank=True, null=True, related_name='collaborator', to='authentication.User'),
        ),
    ]
