# Generated by Django 3.0.8 on 2021-01-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0019_auto_20210120_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='reminder',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
