# Generated by Django 3.0.5 on 2021-01-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201231_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='DOB',
            field=models.DateField(max_length=8, null=True),
        ),
    ]
