# Generated by Django 3.0.5 on 2020-12-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
